### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#77]
__Must have:__
* [ ] README.md
* [ ] docs that do not suck
* [ ] basic tutorial
* [ ] RemoteMixtureOfExperts
* [ ] tools to quickly deploy server
* [ ] tutorial on server configuration
* [ ] averaging gating function over peers

__Nice to have:__
* [ ] tensor packing / quantization
* [ ] visualization tool
* .. move from assorted feature requests

**Comment by louis030195** [comment]
This sounds an interesting project, I like the idea of decentralized computing a bit like cryptocurrencies does, but not for currency, rather for general computing, because computing can be quite expensive.
In my mind it would have looked a bit like a Kubernetes but decentralized, without any security issues regarding others' hardware access and probably based on trading computing for a kind of currency (yes still would be cheaper than current centralized computing clouds), though.

About the roadmap, I see exciting technical details, but I don't see how people will see and find themselves sharing their resources for a common goal?
Is there any plan to develop a UI or something like?

Example: Bob and Alice want to train a GPT3 200B parameters, but Bob can only afford half the training price, same for Alice, but with this awesome UI, they could see that they match into a common goal.

**Comment by borzunov** [comment]
Hi @louis030195!

> probably based on trading computing for a kind of currency

Yeah, there are a couple of projects related to this idea: [vast.ai](https://vast.ai/) provides a service for users to lease/rent each other's GPUs, and [BitTensor](https://bittensor.com/) (cc @unconst) is built around a cryptocurrency serving as an incentive for people who help train models with their GPUs.

Currently, hivemind doesn't involve any financial incentives: we assume that volunteers are motivated by having access to the training outcome and recognition in the leaderboard. However, if time shows that the financial motivation is crucial, hivemind may serve as a backend for BitTensor nodes :)

> I don't see how people will see and find themselves sharing their resources for a common goal?
> Is there any plan to develop a UI or something like?

For now, we assume this happens like this:

- Initial collaborators find each other using our Discord or social media
- They discuss their model/dataset choices and write code responsible for the model and dataset streaming
- They create a page explaining other people how to join and advertise it (e.g., in social media)
- People can follow instructions on the page, joining using their own GPUs or free cloud services like Google Colab

An example of such a page is [our demo](https://training-transformers-together.github.io/) where we train a DALL-E-like model.

However, I definitely agree that our project will benefit from a centralized UI where a new user can see all planned/ongoing training runs and join the ones they consider interesting :)

**Comment by mryab** [comment]
Hi @Coding-Priest, thank you for your interest! There is no ongoing work on that AFAIK, so if you're willing to create a UI with the list of ongoing training runs, feel free to create an issue with a design proposal and take a stab at it!
