### ISSUE TITLE
Faster RemoteMixtureOfExperts beam_search

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/hivemind#92]
Right now, RemoteMixtureOfExperts.beam_search can take hundreds of milliseconds if at least some of DHT peers are slow to respond. This is initially due to two bottlenecks:
* beam search needs a lot of communication between server and local dht node
* dht itself awaits for all peers to respond

Suggestions:

__Move beam search to hivemind.dht.DHT__ (as discussed with @mryab)
Right now, every beam search call invokes hundreds of requests to a DHT. Each request creates a separate MPFuture (pipe-based) which induces communication overhead. Let's instead implement beam search inside hivemind.dht.DHT and only make one request per search (or even per batch).

__Asynchronous beam search__  (as proposed by @unconst)
A beam search for every batch happens in node's local cache. All experts that are not in cache are considered absent for this search, but there is a background process that constantly adds new experts.

Variant: specify a time budget, search across the DHT for up to this many seconds. On hitting the deadline, reuse what you can from cache.

__Better DHT prefixes__ (by @me)
Right now, DHT prefixes are stored as binary entries. This means that if we have a key structure of [0..999].[0..999].[0..999], each beam search step requires 999 requests to a DHT in the worst case.

To avoid this complexity, we can support an additional DHT data type: unordered set.
A key of this type has multiple values with independent expirations.
* on STORE(key, subkey, value, expiration), add (subkey, value) to this set until expiration
* on GET(key), retrieve all entries currently associated with this set

With this data type, we can store prefixes as dictionaries {next_index -> expert}, e.g.
```(python)
DHT["expert.110."] = {
   "1.": "expert.110.1.15",
   "20.": "expert.110.20.119",
   ...
   "248.": "expert.110.248.119"
}
```
So, we no longer need first_k_active: we just retrieve the prefix and it automatically tells us all the active suffixes.

Variant: during traverse_dht, collect all matching dictionaries and combine their keys.

__Negative caching:__(by Dmitry Afanasiev)
Every time a DHT key is not found, add it to a negative cache for T seconds. During that time, all subsequent GET requests return None without search. If a key released from a negative cache and is not found again, add it to a negative cache for 2 * T seconds. When a key is found (or stored on this node), reset the negative cache timer to 0.

Variant: when a key is released from negative cache, search for it in background without stalling the beam search procedure?

**Comment by justheuristic** [comment]
Status, as of right now:
* [ ] improved caching in DHTNode #97
* [ ] implemented new prefix structure for experts ( #103 )
* [ ] beam search now works 10x faster as long as 1st UID dimension is dense ( #111 )
* [ ] formalize a benchmark for beam search performance
* [ ] update tutorial for new beam search
* [ ] figure out why declare_experts is slower
